{
    "optimizeImages": false,
    "previewLevel": "yes",
    "gyroscopeEnabled": false,
    "skinInfo": {
        "title": "Empty",
        "isAdaptableSize": true,
        "class": "SkinInfo"
    },
    "loadingVisible": true,
    "enablePanorama3DTransition": true,
    "publishAutoexecutableWithCompression": false,
    "class": "ShowProject",
    "player": {
        "paddingTop": 0,
        "name": "Player615",
        "toolTipShadowColor": 3355443,
        "toolTipShadowBlurRadius": 3,
        "scrollBarMargin": 2,
        "toolTipFontStyle": "normal",
        "toolTipTextShadowAngle": 0,
        "paddingBottom": 0,
        "id": "rootPlayer",
        "toolTipBackgroundTransparent": false,
        "toolTipTextShadowBlurRadius": 3,
        "mobileMipmappingEnabled": false,
        "overflow": "hidden",
        "paddingLeft": 0,
        "toolTipShadowOpacity": 1,
        "toolTipHorizontalAlign": "center",
        "propagateClick": false,
        "toolTipShadowDistance": 0,
        "backgroundOpacity": 1,
        "toolTipBorderSize": 1,
        "gap": 10,
        "verticalAlign": "top",
        "toolTipFontWeight": "normal",
        "paddingRight": 0,
        "scrollBarWidth": 10,
        "arrangement": "absolute",
        "toolTipFontSize": "1.11vmin",
        "mediaActivationMode": "window",
        "horizontalAlign": "left",
        "toolTipPaddingTop": 4,
        "borderSize": 0,
        "scrollBarVisible": "rollOver",
        "toolTipShadowSpread": 0,
        "device2Children": {
            "general": [
                "this.MainViewer"
            ]
        },
        "scrollBarOpacity": 0.5,
        "toolTipBorderColor": 7763574,
        "downloadEnabled": false,
        "desktopMipmappingEnabled": false,
        "toolTipPaddingLeft": 6,
        "defaultVRPointer": "laser",
        "backgroundColor": [
            16777215
        ],
        "toolTipShadowAngle": 45,
        "width": "100%",
        "toolTipOpacity": 1,
        "height": "100%",
        "asHotspotVideo": false,
        "vrPolyfillScale": 0.75,
        "toolTipBorderRadius": 3,
        "toolTipTextShadowDistance": 0,
        "minHeight": 20,
        "scrollBarColor": 0,
        "backgroundColorAlphas": [
            1
        ],
        "minWidth": 20,
        "toolTipPaddingBottom": 4,
        "borderRadius": 0,
        "shadow": false,
        "landscapeModeMobile": "mobile",
        "percentHeight": 100,
        "percentWidth": 100,
        "toolTipTextShadowOpacity": 0,
        "contentOpaque": false,
        "definitions": [
            {
                "name": "Main Viewer",
                "visible": true,
                "toolTipTextShadowSpread": 0,
                "subtitlesFontColor": 16777215,
                "class": "ViewerAreaLabeled",
                "progressRight": 0,
                "id": "MainViewer",
                "toolTipShadowOpacity": 1,
                "playbackBarBorderRadius": 0,
                "playbackBarHeadBackgroundColorRatios": [
                    0,
                    255
                ],
                "playbackBarBorderColor": 16777215,
                "progressBarBorderSize": 0,
                "playbackBarProgressBorderColor": 0,
                "playbackBarHeadBorderSize": 0,
                "subtitlesFontWeight": "normal",
                "progressOpacity": 1,
                "subtitlesShadowOpacity": 0.6,
                "toolTipFontWeight": "normal",
                "playbackBarHeadShadowDistance": 0,
                "subtitlesPaddingLeft": 5,
                "playbackBarHeadBorderRadius": 0,
                "surfaceReticleSelectionOpacity": 1,
                "subtitlesTextShadowOpacity": 1,
                "subtitlesPaddingRight": 5,
                "borderSize": 0,
                "subtitlesBottom": 50,
                "playbackBarHeadOpacity": 1,
                "progressBackgroundColorRatios": [
                    0
                ],
                "vrPointerSelectionTime": 2000,
                "progressBorderRadius": 0,
                "subtitlesTop": 0,
                "backgroundColor": [
                    5739774,
                    26061
                ],
                "toolTipShadowAngle": 45,
                "playbackBarHeadShadow": true,
                "playbackBarProgressOpacity": 1,
                "subtitlesTextShadowDistance": 1,
                "subtitlesShadowBlurRadius": 3,
                "subtitlesTextShadowColor": 0,
                "playbackBarHeadBorderColor": 0,
                "playbackBarHeadShadowAngle": 0,
                "toolTipBorderRadius": 3,
                "progressLeft": 0,
                "surfaceReticleColor": 16777215,
                "subtitlesFontSize": "3vmin",
                "firstTransitionDuration": 0,
                "backgroundColorAlphas": [
                    1,
                    1
                ],
                "playbackBarBorderSize": 0,
                "toolTipPaddingBottom": 4,
                "surfaceReticleOpacity": 0.6,
                "playbackBarOpacity": 1,
                "shadow": false,
                "progressBarBackgroundColorDirection": "vertical",
                "playbackBarHeadBackgroundColor": [
                    1118481,
                    6710886
                ],
                "subtitlesBackgroundOpacity": 0.2,
                "subtitlesPaddingBottom": 5,
                "toolTipTextShadowOpacity": 0,
                "displayTooltipInTouchScreens": true,
                "vrPointerSelectionColor": 16737792,
                "backgroundColorDirection": "vertical",
                "progressBarBorderColor": 0,
                "paddingTop": 0,
                "playbackBarBottom": 5,
                "toolTipDisplayTime": 600,
                "paddingBottom": 0,
                "subtitlesTextShadowAngle": 45,
                "playbackBarBackgroundOpacity": 1,
                "progressBarBackgroundColorRatios": [
                    0
                ],
                "playbackBarProgressBackgroundColorDirection": "vertical",
                "progressBackgroundOpacity": 1,
                "toolTipShadowColor": 3355443,
                "toolTipShadowBlurRadius": 3,
                "toolTipTextShadowColor": 0,
                "subtitlesBorderColor": 16777215,
                "transitionMode": "blending",
                "toolTipTextShadowAngle": 0,
                "toolTipFontColor": 6316128,
                "toolTipBackgroundTransparent": false,
                "toolTipTextShadowBlurRadius": 3,
                "playbackBarHeight": 10,
                "progressBackgroundColorDirection": "vertical",
                "playbackBarBackgroundColor": [
                    16777215
                ],
                "paddingLeft": 0,
                "playbackBarHeadBackgroundColorDirection": "vertical",
                "toolTipHorizontalAlign": "center",
                "toolTipShadowDistance": 0,
                "backgroundOpacity": 1,
                "subtitlesTextDecoration": "none",
                "toolTipBorderSize": 1,
                "playbackBarProgressBorderSize": 0,
                "playbackBarHeadWidth": 6,
                "paddingRight": 0,
                "transitionDuration": 500,
                "subtitlesTextShadowBlurRadius": 0,
                "toolTipFontSize": "1.11vmin",
                "toolTipPaddingTop": 4,
                "playbackBarBackgroundColorDirection": "vertical",
                "progressBorderColor": 0,
                "subtitlesShadowDistance": 1,
                "toolTipShadowSpread": 0,
                "progressBarBackgroundColor": [
                    3381759
                ],
                "toolTipBorderColor": 7763574,
                "playbackBarRight": 0,
                "toolTipPaddingLeft": 6,
                "playbackBarProgressBackgroundColor": [
                    3381759
                ],
                "playbackBarProgressBorderRadius": 0,
                "progressBackgroundColor": [
                    16777215
                ],
                "subtitlesShadow": false,
                "subtitlesFontFamily": "Arial",
                "subtitlesPaddingTop": 5,
                "toolTipOpacity": 1,
                "subtitlesShadowAngle": 45,
                "surfaceReticleSelectionColor": 16777215,
                "asHotspotVideo": false,
                "playbackBarHeadShadowOpacity": 0.7,
                "toolTipTextShadowDistance": 0,
                "minHeight": 50,
                "subtitlesOpacity": 1,
                "progressBarOpacity": 1,
                "minWidth": 100,
                "progressBottom": 0,
                "borderRadius": 0,
                "vrPointerColor": 16777215,
                "subtitlesGap": 0,
                "percentHeight": 100,
                "playbackBarHeadShadowBlurRadius": 3,
                "subtitlesBackgroundColor": 0,
                "progressHeight": 10,
                "percentWidth": 100,
                "subtitlesHorizontalAlign": "center",
                "progressBorderSize": 0,
                "subtitlesShadowColor": 0,
                "subtitlesVerticalAlign": "bottom",
                "playbackBarLeft": 0,
                "toolTipFontStyle": "normal",
                "progressBarBorderRadius": 0,
                "toolTipPaddingRight": 6,
                "backgroundColorRatios": [
                    0,
                    255
                ],
                "playbackBarHeadShadowColor": 0,
                "playbackBarProgressBackgroundColorRatios": [
                    0
                ],
                "playbackBarHeadHeight": 15,
                "subtitlesBorderSize": 0,
                "propagateClick": false,
                "playbackBarBackgroundColorRatios": [
                    0
                ],
                "toolTipFontFamily": "Arial",
                "toolTipBackgroundColor": 16185078
            },
            {
                "exportHeight": 2688,
                "vfov": 180,
                "camera": "this.panorama_15A56E73_1F5D_3F9D_41BE_F5F2D1ABC4FE_camera",
                "frames": [
                    {
                        "class": "CubicPanoramaFrame"
                    }
                ],
                "stopGlobalMusic": false,
                "id": "panorama_15A56E73_1F5D_3F9D_41BE_F5F2D1ABC4FE",
                "pose": {
                    "roll": 0,
                    "yaw": 0,
                    "pitch": 0,
                    "class": "PanoramaPose"
                },
                "quality": 75,
                "width": 5376,
                "hfovMax": 130,
                "hasChanges": true,
                "pitch": 0,
                "class": "PanoramaEditable",
                "paths": [
                    "R0010547.jpg"
                ],
                "hfov": 360,
                "hfovMin": "150%",
                "sourceType": "erect",
                "height": 2688,
                "exportWidth": 5376
            },
            {
                "exportHeight": 2688,
                "vfov": 180,
                "camera": "this.panorama_162884BA_1F5D_EC8C_419C_895D4ABA88D3_camera",
                "frames": [
                    {
                        "class": "CubicPanoramaFrame"
                    }
                ],
                "stopGlobalMusic": false,
                "id": "panorama_162884BA_1F5D_EC8C_419C_895D4ABA88D3",
                "pose": {
                    "roll": 0,
                    "yaw": 0,
                    "pitch": 0,
                    "class": "PanoramaPose"
                },
                "quality": 75,
                "width": 5376,
                "hfovMax": 130,
                "hasChanges": true,
                "pitch": 0,
                "class": "PanoramaEditable",
                "paths": [
                    "R0010548.jpg"
                ],
                "hfov": 360,
                "hfovMin": "150%",
                "sourceType": "erect",
                "height": 2688,
                "exportWidth": 5376
            },
            {
                "paddingTop": 10,
                "name": "HTMLText614",
                "toolTipShadowColor": 3355443,
                "toolTipShadowBlurRadius": 3,
                "scrollBarMargin": 2,
                "pixelsPerUnitH": 10.8,
                "toolTipTextShadowAngle": 0,
                "paddingBottom": 10,
                "id": "HTMLText_1650EC48_1F5D_238B_41AA_25D32693BE41",
                "left": "0%",
                "toolTipTextShadowBlurRadius": 3,
                "paddingLeft": 10,
                "toolTipShadowOpacity": 1,
                "toolTipBackgroundTransparent": false,
                "propagateClick": false,
                "toolTipShadowDistance": 0,
                "backgroundOpacity": 0,
                "toolTipBorderSize": 1,
                "toolTipFontWeight": "normal",
                "paddingRight": 10,
                "scrollBarWidth": 10,
                "toolTipFontSize": "1.11vmin",
                "toolTipHorizontalAlign": "center",
                "toolTipPaddingTop": 4,
                "borderSize": 0,
                "scrollBarVisible": "rollOver",
                "toolTipShadowSpread": 0,
                "scrollBarOpacity": 0.5,
                "top": "50%",
                "toolTipBorderColor": 7763574,
                "toolTipPaddingLeft": 6,
                "toolTipShadowAngle": 45,
                "toolTipOpacity": 1,
                "asHotspotVideo": false,
                "toolTipBorderRadius": 3,
                "fontSizeUnit": "vmin",
                "toolTipTextShadowDistance": 0,
                "minHeight": 0,
                "scrollBarColor": 0,
                "minWidth": 0,
                "toolTipPaddingBottom": 4,
                "borderRadius": 0,
                "shadow": false,
                "pixelsPerUnitW": 19.2,
                "percentHeight": 10,
                "percentWidth": 100,
                "toolTipTextShadowOpacity": 0,
                "toolTipFontFamily": "Arial",
                "toolTipDisplayTime": 600,
                "visible": true,
                "toolTipPaddingRight": 6,
                "toolTipFontStyle": "normal",
                "toolTipBackgroundColor": 16185078,
                "toolTipFontColor": 6316128,
                "toolTipTextShadowSpread": 0,
                "toolTipTextShadowColor": 0,
                "class": "HTMLText"
            },
            {
                "automaticRotationSpeed": 10,
                "manualRotationSpeed": 1800,
                "initialPosition": {
                    "yaw": 0,
                    "pitch": 0,
                    "class": "PanoramaCameraPosition"
                },
                "class": "PanoramaCamera",
                "manualZoomSpeed": 1,
                "id": "panorama_15A56E73_1F5D_3F9D_41BE_F5F2D1ABC4FE_camera",
                "automaticZoomSpeed": 10,
                "initialSequence": "this.sequence_16D6CF6A_1F5D_FD8F_41BE_3CA6912D81B6"
            },
            {
                "automaticRotationSpeed": 10,
                "manualRotationSpeed": 1800,
                "initialPosition": {
                    "yaw": 0,
                    "pitch": 0,
                    "class": "PanoramaCameraPosition"
                },
                "class": "PanoramaCamera",
                "manualZoomSpeed": 1,
                "id": "panorama_162884BA_1F5D_EC8C_419C_895D4ABA88D3_camera",
                "automaticZoomSpeed": 10,
                "initialSequence": "this.sequence_16D27F6B_1F5D_FD8D_41B1_7091E6958819"
            },
            {
                "yawSpeedPercent": 0.15,
                "restartMovementOnUserInteraction": false,
                "laps": 1,
                "class": "PanoramaCameraLoopSequence",
                "moveToHorizon": false,
                "inertiaFunction": "cubic",
                "direction": "right",
                "id": "sequence_16D6CF6A_1F5D_FD8F_41BE_3CA6912D81B6",
                "inertiaSpeedPercent": 0.5,
                "withAcceleration": true
            },
            {
                "yawSpeedPercent": 0.15,
                "restartMovementOnUserInteraction": false,
                "laps": 1,
                "class": "PanoramaCameraLoopSequence",
                "moveToHorizon": false,
                "inertiaFunction": "cubic",
                "direction": "right",
                "id": "sequence_16D27F6B_1F5D_FD8D_41B1_7091E6958819",
                "inertiaSpeedPercent": 0.5,
                "withAcceleration": true
            }
        ],
        "backgroundColorDirection": "vertical",
        "backgroundColorRatios": [
            0
        ],
        "backgroundPreloadEnabled": true,
        "toolTipDisplayTime": 600,
        "visible": true,
        "toolTipPaddingRight": 6,
        "toolTipFontFamily": "Arial",
        "mouseWheelEnabled": true,
        "toolTipBackgroundColor": 16185078,
        "toolTipFontColor": 6316128,
        "toolTipTextShadowSpread": 0,
        "toolTipTextShadowColor": 0,
        "class": "Player"
    },
    "publishVideo360Properties": {},
    "medias": [
        "this.panorama_15A56E73_1F5D_3F9D_41BE_F5F2D1ABC4FE",
        "this.panorama_162884BA_1F5D_EC8C_419C_895D4ABA88D3"
    ],
    "surfaceSelectionSensitivity": 1,
    "tdvHostingCredentials": {
        "class": "TDVHostingCredentials"
    },
    "panoramaZoomEnabled": true,
    "surfaceSelectionHotspotMode": "circleEnabled",
    "publishVideo360": false,
    "muteSoundAtStart": false,
    "publishAutoexecutable": false,
    "displayTooltipInTouchScreens": true,
    "enableTdvTourAnalytics": false,
    "optimizeForVR": true,
    "analyticsAnonymizeIP": true,
    "publishAutoexecutableWindows": true,
    "initialScale": 0.5,
    "publishScorm": false,
    "publishWeb": true,
    "include360SocialIcon": true,
    "panoramaTouchControlMode": "drag_rotation",
    "surfaceSelectionEnabled": false,
    "publishAutoexecutableMac": true,
    "exportVideoToAdaptive": false,
    "displayTooltipInSurfaceSelection": true,
    "additionalMedias": [],
    "publishGSV": false,
    "enableLocaleAutodetection": true,
    "enableSubtitles": true,
    "publishTDVCloud": false,
    "gyroscopeVerticalDraggingEnabled": true,
    "locales": [
        {
            "language": "ja",
            "data": {
                "panorama_162884BA_1F5D_EC8C_419C_895D4ABA88D3.label": {
                    "value": "R0010548",
                    "class": "LocaleValue"
                },
                "HTMLText_1650EC48_1F5D_238B_41AA_25D32693BE41.html": {
                    "value": "<P ALIGN=\"center\"><FONT FACE=\"Arial\" SIZE=\"1.6666666666666665vmin\" COLOR=\"#777777\" LETTERSPACING=\"0vmin\" KERNING=\"1\">Loading virtual tour. Please wait...</FONT></P>",
                    "class": "LocaleValue"
                },
                "tour.name": {
                    "value": "Untitled 244",
                    "class": "LocaleValue"
                },
                "panorama_15A56E73_1F5D_3F9D_41BE_F5F2D1ABC4FE.label": {
                    "value": "R0010547",
                    "class": "LocaleValue"
                }
            },
            "class": "Locale"
        }
    ],
    "exportiOSLegacy": false,
    "preloadPlayer": {
        "paddingTop": 0,
        "name": "Player613",
        "toolTipShadowColor": 3355443,
        "toolTipShadowBlurRadius": 3,
        "scrollBarMargin": 2,
        "toolTipFontStyle": "normal",
        "toolTipTextShadowAngle": 0,
        "paddingBottom": 0,
        "id": "Player_15EA46AB_1F5D_2C8D_41B4_0843E5EF4093",
        "toolTipBackgroundTransparent": false,
        "toolTipTextShadowBlurRadius": 3,
        "mobileMipmappingEnabled": false,
        "overflow": "hidden",
        "paddingLeft": 0,
        "toolTipShadowOpacity": 1,
        "toolTipHorizontalAlign": "center",
        "propagateClick": false,
        "toolTipShadowDistance": 0,
        "backgroundOpacity": 1,
        "toolTipBorderSize": 1,
        "gap": 10,
        "verticalAlign": "top",
        "toolTipFontWeight": "normal",
        "paddingRight": 0,
        "scrollBarWidth": 10,
        "arrangement": "absolute",
        "toolTipFontSize": "1.11vmin",
        "mediaActivationMode": "window",
        "horizontalAlign": "left",
        "toolTipPaddingTop": 4,
        "borderSize": 0,
        "scrollBarVisible": "rollOver",
        "toolTipShadowSpread": 0,
        "device2Children": {
            "general": [
                "this.HTMLText_1650EC48_1F5D_238B_41AA_25D32693BE41"
            ]
        },
        "scrollBarOpacity": 0.5,
        "toolTipBorderColor": 7763574,
        "downloadEnabled": false,
        "desktopMipmappingEnabled": false,
        "toolTipPaddingLeft": 6,
        "defaultVRPointer": "laser",
        "backgroundColor": [
            16777215
        ],
        "toolTipShadowAngle": 45,
        "width": "100%",
        "toolTipOpacity": 1,
        "height": "100%",
        "asHotspotVideo": false,
        "vrPolyfillScale": 0.75,
        "toolTipBorderRadius": 3,
        "toolTipTextShadowDistance": 0,
        "minHeight": 20,
        "scrollBarColor": 0,
        "backgroundColorAlphas": [
            1
        ],
        "minWidth": 20,
        "toolTipPaddingBottom": 4,
        "borderRadius": 0,
        "shadow": false,
        "landscapeModeMobile": "mobile",
        "percentHeight": 100,
        "percentWidth": 100,
        "toolTipTextShadowOpacity": 0,
        "contentOpaque": false,
        "definitions": [],
        "backgroundColorDirection": "vertical",
        "backgroundColorRatios": [
            0
        ],
        "backgroundPreloadEnabled": true,
        "toolTipDisplayTime": 600,
        "visible": true,
        "toolTipPaddingRight": 6,
        "toolTipFontFamily": "Arial",
        "mouseWheelEnabled": true,
        "toolTipBackgroundColor": 16185078,
        "toolTipFontColor": 6316128,
        "toolTipTextShadowSpread": 0,
        "toolTipTextShadowColor": 0,
        "class": "Player"
    },
    "showVRMenu": false,
    "initializationMode": "onReady",
    "uid": "17A37C40-1F5D-23FB-41AD-513F8812AC02",
    "mainPlayListSameSpotForPanoramas": false,
    "forceGeneralSkinIPad": false,
    "textToSpeechConfig": {
        "pitch": 1,
        "class": "TextToSpeechConfig",
        "stopBackgroundAudio": false,
        "speechOnTooltip": false,
        "speechOnQuizQuestion": false,
        "speechOnInfoWindow": false,
        "rate": 1,
        "volume": 1
    },
    "saveAs": "C:\\Users\\root\\Documents\\test_NOVA - コピー\\3dview_automation\\3dvista_edit_code_new\\test.vtp",
    "arrowKeysAction": "translate",
    "panoramaMouseControlMode": "drag_rotation"
}