{
  "optimizeImages": false,
  "displayTooltipInTouchScreens": true,
  "gyroscopeEnabled": false,
  "skinInfo": {
    "class": "SkinInfo",
    "title": "Empty",
    "isAdaptableSize": true
  },
  "loadingVisible": true,
  "enablePanorama3DTransition": true,
  "showVRMenu": false,
  "panoramaMouseControlMode": "drag_rotation",
  "player": {
    "vrPolyfillScale": 0.75,
    "name": "Player615",
    "toolTipShadowColor": 3355443,
    "toolTipShadowBlurRadius": 3,
    "scrollBarMargin": 2,
    "toolTipFontStyle": "normal",
    "toolTipTextShadowAngle": 0,
    "paddingBottom": 0,
    "id": "rootPlayer",
    "toolTipBackgroundTransparent": false,
    "toolTipTextShadowBlurRadius": 3,
    "overflow": "hidden",
    "paddingLeft": 0,
    "toolTipShadowOpacity": 1,
    "toolTipHorizontalAlign": "center",
    "propagateClick": false,
    "toolTipShadowDistance": 0,
    "backgroundOpacity": 1,
    "toolTipBorderSize": 1,
    "gap": 10,
    "verticalAlign": "top",
    "toolTipFontWeight": "normal",
    "paddingRight": 0,
    "defaultVRPointer": "laser",
    "scrollBarWidth": 10,
    "arrangement": "absolute",
    "toolTipFontSize": "1.11vmin",
    "mediaActivationMode": "window",
    "horizontalAlign": "left",
    "toolTipPaddingTop": 4,
    "borderSize": 0,
    "scrollBarVisible": "rollOver",
    "toolTipShadowSpread": 0,
    "device2Children": {
      "general": [
        "this.MainViewer"
      ]
    },
    "scrollBarOpacity": 0.5,
    "toolTipBorderColor": 7763574,
    "downloadEnabled": false,
    "class": "Player",
    "toolTipPaddingLeft": 6,
    "mobileMipmappingEnabled": false,
    "backgroundColor": [
      16777215
    ],
    "toolTipShadowAngle": 45,
    "width": "100%",
    "toolTipOpacity": 1,
    "height": "100%",
    "asHotspotVideo": false,
    "toolTipBorderRadius": 3,
    "toolTipTextShadowDistance": 0,
    "minHeight": 20,
    "scrollBarColor": 0,
    "backgroundColorAlphas": [
      1
    ],
    "minWidth": 20,
    "toolTipPaddingBottom": 4,
    "borderRadius": 0,
    "shadow": false,
    "landscapeModeMobile": "mobile",
    "percentHeight": 100,
    "percentWidth": 100,
    "toolTipTextShadowOpacity": 0,
    "contentOpaque": false,
    "definitions": [
      {
        "name": "Main Viewer",
        "visible": true,
        "toolTipTextShadowSpread": 0,
        "subtitlesFontColor": 16777215,
        "subtitlesTextShadowOpacity": 1,
        "progressRight": 0,
        "id": "MainViewer",
        "toolTipShadowOpacity": 1,
        "playbackBarBorderRadius": 0,
        "playbackBarHeadBackgroundColorRatios": [
          0,
          255
        ],
        "playbackBarBorderColor": 16777215,
        "progressBarBorderSize": 0,
        "playbackBarProgressBorderColor": 0,
        "playbackBarHeadBorderSize": 0,
        "subtitlesFontWeight": "normal",
        "progressOpacity": 1,
        "subtitlesShadowOpacity": 0.6,
        "toolTipFontWeight": "normal",
        "playbackBarHeadShadowDistance": 0,
        "subtitlesPaddingLeft": 5,
        "playbackBarHeadBorderRadius": 0,
        "surfaceReticleSelectionOpacity": 1,
        "subtitlesPaddingRight": 5,
        "borderSize": 0,
        "subtitlesBottom": 50,
        "playbackBarHeadOpacity": 1,
        "progressBackgroundColorRatios": [
          0
        ],
        "class": "ViewerAreaLabeled",
        "subtitlesTop": 0,
        "backgroundColor": [
          5739774,
          26061
        ],
        "toolTipShadowAngle": 45,
        "playbackBarHeadShadow": true,
        "progressBorderRadius": 0,
        "playbackBarProgressOpacity": 1,
        "subtitlesTextShadowDistance": 1,
        "subtitlesShadowBlurRadius": 3,
        "subtitlesTextShadowColor": 0,
        "playbackBarHeadBorderColor": 0,
        "playbackBarHeadShadowAngle": 0,
        "toolTipBorderRadius": 3,
        "progressLeft": 0,
        "surfaceReticleColor": 16777215,
        "subtitlesFontSize": "3vmin",
        "firstTransitionDuration": 0,
        "backgroundColorAlphas": [
          1,
          1
        ],
        "playbackBarBorderSize": 0,
        "toolTipPaddingBottom": 4,
        "surfaceReticleOpacity": 0.6,
        "playbackBarOpacity": 1,
        "shadow": false,
        "progressBarBackgroundColorDirection": "vertical",
        "playbackBarHeadBackgroundColor": [
          1118481,
          6710886
        ],
        "subtitlesBackgroundOpacity": 0.2,
        "subtitlesPaddingBottom": 5,
        "toolTipTextShadowOpacity": 0,
        "displayTooltipInTouchScreens": true,
        "backgroundColorDirection": "vertical",
        "progressBarBorderColor": 0,
        "toolTipDisplayTime": 600,
        "playbackBarBottom": 5,
        "vrPointerSelectionTime": 2000,
        "paddingTop": 0,
        "paddingBottom": 0,
        "subtitlesTextShadowAngle": 45,
        "playbackBarBackgroundOpacity": 1,
        "progressBarBackgroundColorRatios": [
          0
        ],
        "playbackBarProgressBackgroundColorDirection": "vertical",
        "progressBackgroundOpacity": 1,
        "toolTipShadowColor": 3355443,
        "toolTipShadowBlurRadius": 3,
        "toolTipTextShadowColor": 0,
        "subtitlesBorderColor": 16777215,
        "transitionMode": "blending",
        "toolTipTextShadowAngle": 0,
        "toolTipFontColor": 6316128,
        "toolTipBackgroundTransparent": false,
        "toolTipTextShadowBlurRadius": 3,
        "playbackBarHeight": 10,
        "progressBackgroundColorDirection": "vertical",
        "playbackBarBackgroundColor": [
          16777215
        ],
        "paddingLeft": 0,
        "playbackBarHeadBackgroundColorDirection": "vertical",
        "vrPointerColor": 16777215,
        "toolTipHorizontalAlign": "center",
        "vrPointerSelectionColor": 16737792,
        "toolTipShadowDistance": 0,
        "backgroundOpacity": 1,
        "subtitlesTextDecoration": "none",
        "toolTipBorderSize": 1,
        "playbackBarProgressBorderSize": 0,
        "playbackBarHeadWidth": 6,
        "paddingRight": 0,
        "transitionDuration": 500,
        "subtitlesTextShadowBlurRadius": 0,
        "toolTipFontSize": "1.11vmin",
        "toolTipPaddingTop": 4,
        "playbackBarBackgroundColorDirection": "vertical",
        "progressBorderColor": 0,
        "subtitlesShadowDistance": 1,
        "toolTipShadowSpread": 0,
        "progressBarBackgroundColor": [
          3381759
        ],
        "toolTipBorderColor": 7763574,
        "playbackBarRight": 0,
        "toolTipPaddingLeft": 6,
        "playbackBarProgressBackgroundColor": [
          3381759
        ],
        "playbackBarProgressBorderRadius": 0,
        "progressBackgroundColor": [
          16777215
        ],
        "subtitlesShadow": false,
        "subtitlesFontFamily": "Arial",
        "subtitlesPaddingTop": 5,
        "toolTipOpacity": 1,
        "subtitlesShadowAngle": 45,
        "surfaceReticleSelectionColor": 16777215,
        "asHotspotVideo": false,
        "playbackBarHeadShadowOpacity": 0.7,
        "toolTipTextShadowDistance": 0,
        "minHeight": 50,
        "subtitlesOpacity": 1,
        "progressBarOpacity": 1,
        "minWidth": 100,
        "progressBottom": 0,
        "borderRadius": 0,
        "subtitlesGap": 0,
        "percentHeight": 100,
        "playbackBarHeadShadowBlurRadius": 3,
        "subtitlesBackgroundColor": 0,
        "progressHeight": 10,
        "percentWidth": 100,
        "subtitlesHorizontalAlign": "center",
        "progressBorderSize": 0,
        "subtitlesShadowColor": 0,
        "subtitlesVerticalAlign": "bottom",
        "playbackBarLeft": 0,
        "toolTipFontStyle": "normal",
        "progressBarBorderRadius": 0,
        "toolTipPaddingRight": 6,
        "backgroundColorRatios": [
          0,
          255
        ],
        "playbackBarHeadShadowColor": 0,
        "playbackBarProgressBackgroundColorRatios": [
          0
        ],
        "playbackBarHeadHeight": 15,
        "subtitlesBorderSize": 0,
        "propagateClick": false,
        "playbackBarBackgroundColorRatios": [
          0
        ],
        "toolTipFontFamily": "Arial",
        "toolTipBackgroundColor": 16185078
      },
      {
        "hfov": 360,
        "exportHeight": 2688,
        "vfov": 180,
        "camera": "this.panorama_44D4D1A2_4E21_7B73_41CC_EDE1070CE037_camera",
        "frames": [
          {
            "class": "CubicPanoramaFrame"
          }
        ],
        "stopGlobalMusic": false,
        "id": "panorama_44D4D1A2_4E21_7B73_41CC_EDE1070CE037",
        "pose": {
          "class": "PanoramaPose",
          "roll": 0,
          "yaw": 0,
          "pitch": 0
        },
        "quality": 75,
        "width": 5376,
        "hfovMax": 130,
        "hasChanges": true,
        "pitch": 0,
        "paths": [
          "file:///C:/Users/root/Documents/walk/3dview_automation/3dvista_edit_code_new/Images/R0010547.jpg"
        ],
        "class": "PanoramaEditable",
        "hfovMin": "150%",
        "sourceType": "erect",
        "height": 2688,
        "exportWidth": 5376,
        "overlays": [
          "this.overlay_C0_0",
          "this.overlay_D0_0",
          "this.popup_D0_0",
          "this.overlay_D0_1",
          "this.popup_D0_1"
        ]
      },
      {
        "hfov": 360,
        "exportHeight": 2688,
        "vfov": 180,
        "camera": "this.panorama_47FE5A9D_4E21_4956_41A5_92D82D1E8740_camera",
        "frames": [
          {
            "class": "CubicPanoramaFrame"
          }
        ],
        "stopGlobalMusic": false,
        "id": "panorama_47FE5A9D_4E21_4956_41A5_92D82D1E8740",
        "pose": {
          "class": "PanoramaPose",
          "roll": 0,
          "yaw": 0,
          "pitch": 0
        },
        "quality": 75,
        "width": 5376,
        "hfovMax": 130,
        "hasChanges": true,
        "pitch": 0,
        "paths": [
          "file:///C:/Users/root/Documents/walk/3dview_automation/3dvista_edit_code_new/Images/R0010548.jpg"
        ],
        "class": "PanoramaEditable",
        "hfovMin": "150%",
        "sourceType": "erect",
        "height": 2688,
        "exportWidth": 5376,
        "overlays": [
          "this.overlay_C1_0"
        ]
      },
      {
        "name": "HTMLText614",
        "toolTipShadowColor": 3355443,
        "toolTipShadowBlurRadius": 3,
        "scrollBarMargin": 2,
        "pixelsPerUnitH": 10.8,
        "toolTipTextShadowAngle": 0,
        "paddingBottom": 10,
        "id": "HTMLText_4720EEBE_4E20_C952_41AF_2A8B54294CA0",
        "left": "0%",
        "toolTipTextShadowBlurRadius": 3,
        "paddingLeft": 10,
        "toolTipShadowOpacity": 1,
        "toolTipBackgroundTransparent": false,
        "propagateClick": false,
        "toolTipShadowDistance": 0,
        "backgroundOpacity": 0,
        "toolTipBorderSize": 1,
        "toolTipFontWeight": "normal",
        "paddingRight": 10,
        "scrollBarWidth": 10,
        "toolTipFontSize": "1.11vmin",
        "toolTipHorizontalAlign": "center",
        "toolTipPaddingTop": 4,
        "borderSize": 0,
        "scrollBarVisible": "rollOver",
        "toolTipShadowSpread": 0,
        "scrollBarOpacity": 0.5,
        "top": "50%",
        "toolTipBorderColor": 7763574,
        "class": "HTMLText",
        "toolTipPaddingLeft": 6,
        "toolTipShadowAngle": 45,
        "toolTipOpacity": 1,
        "asHotspotVideo": false,
        "toolTipBorderRadius": 3,
        "fontSizeUnit": "vmin",
        "toolTipTextShadowDistance": 0,
        "minHeight": 0,
        "scrollBarColor": 0,
        "minWidth": 0,
        "toolTipPaddingBottom": 4,
        "borderRadius": 0,
        "shadow": false,
        "pixelsPerUnitW": 19.2,
        "percentHeight": 10,
        "percentWidth": 100,
        "toolTipTextShadowOpacity": 0,
        "toolTipFontFamily": "Arial",
        "toolTipDisplayTime": 600,
        "visible": true,
        "toolTipPaddingRight": 6,
        "toolTipFontStyle": "normal",
        "paddingTop": 10,
        "toolTipFontColor": 6316128,
        "toolTipTextShadowSpread": 0,
        "toolTipTextShadowColor": 0,
        "toolTipBackgroundColor": 16185078
      },
      {
        "automaticRotationSpeed": 10,
        "manualZoomSpeed": 1,
        "manualRotationSpeed": 1800,
        "initialPosition": {
          "class": "PanoramaCameraPosition",
          "yaw": 0,
          "pitch": 0
        },
        "class": "PanoramaCamera",
        "id": "panorama_44D4D1A2_4E21_7B73_41CC_EDE1070CE037_camera",
        "automaticZoomSpeed": 10,
        "initialSequence": "this.sequence_47D4E331_4E21_5F51_4191_152E592AEF01"
      },
      {
        "automaticRotationSpeed": 10,
        "manualZoomSpeed": 1,
        "manualRotationSpeed": 1800,
        "initialPosition": {
          "class": "PanoramaCameraPosition",
          "yaw": 0,
          "pitch": 0
        },
        "class": "PanoramaCamera",
        "id": "panorama_47FE5A9D_4E21_4956_41A5_92D82D1E8740_camera",
        "automaticZoomSpeed": 10,
        "initialSequence": "this.sequence_47D87332_4E21_5F53_41C4_15164E718F3C"
      },
      {
        "yawSpeedPercent": 0.15,
        "direction": "right",
        "restartMovementOnUserInteraction": false,
        "laps": 1,
        "moveToHorizon": false,
        "class": "PanoramaCameraLoopSequence",
        "inertiaFunction": "cubic",
        "id": "sequence_47D4E331_4E21_5F51_4191_152E592AEF01",
        "inertiaSpeedPercent": 0.5,
        "withAcceleration": true
      },
      {
        "yawSpeedPercent": 0.15,
        "direction": "right",
        "restartMovementOnUserInteraction": false,
        "laps": 1,
        "moveToHorizon": false,
        "class": "PanoramaCameraLoopSequence",
        "inertiaFunction": "cubic",
        "id": "sequence_47D87332_4E21_5F53_41C4_15164E718F3C",
        "inertiaSpeedPercent": 0.5,
        "withAcceleration": true
      },
      {
        "areas": [
          "this.HotspotPanoramaOverlayArea_C0_0"
        ],
        "class": "HotspotPanoramaOverlayEditable",
        "excludeClickGoMode": false,
        "items": [
          {
            "visibleOnStop": false,
            "playEvent": "start",
            "label": "Arrow 01",
            "verticalAlign": "middle",
            "width": 33.33333333333333,
            "loop": true,
            "path": "hotspots/Hotspot_34559710_3D00_0B16_41B3_160403C9DC33.png",
            "showFrameAtStart": 0,
            "stopEvent": "none",
            "class": "HotspotPanoramaOverlayAnimatedBitmapImage",
            "libraryData": {
              "type": "goToPanoramaWall",
              "name": "arrow01",
              "element": "IHotspotOverlayBitmapImage",
              "family": "animated"
            },
            "pitch": -30,
            "hfov": 7.616601683506721,
            "yaw": 21.095410192211805,
            "pauseEvent": "none",
            "x": 1318.513955550577,
            "fps": 16,
            "y": 483,
            "horizontalAlign": "center",
            "scaleMode": "fit_inside",
            "transparencyActive": true,
            "factorHeight": 3.751570132588974,
            "distance": 100,
            "height": 30,
            "factorWidth": 3.751570132588974
          }
        ],
        "rollOverDisplay": false,
        "useHandCursor": true,
        "maps": [],
        "id": "overlay_C0_0",
        "hasChanges": true
      },
      {
        "areas": [
          "this.HotspotPanoramaOverlayArea_C1_0"
        ],
        "class": "HotspotPanoramaOverlayEditable",
        "excludeClickGoMode": false,
        "items": [
          {
            "visibleOnStop": false,
            "playEvent": "start",
            "label": "Arrow 01",
            "verticalAlign": "middle",
            "width": 33.33333333333333,
            "loop": true,
            "path": "hotspots/Hotspot_34559710_3D00_0B16_41B3_160403C9DC33.png",
            "showFrameAtStart": 0,
            "stopEvent": "none",
            "class": "HotspotPanoramaOverlayAnimatedBitmapImage",
            "libraryData": {
              "type": "goToPanoramaWall",
              "name": "arrow01",
              "element": "IHotspotOverlayBitmapImage",
              "family": "animated"
            },
            "pitch": -30,
            "hfov": 7.616601683506721,
            "yaw": -158.9045898077882,
            "pauseEvent": "none",
            "x": 628.597784636497,
            "fps": 16,
            "y": 483,
            "horizontalAlign": "center",
            "scaleMode": "fit_inside",
            "transparencyActive": true,
            "factorHeight": 3.751570132588974,
            "distance": 100,
            "height": 30,
            "factorWidth": 3.751570132588974
          }
        ],
        "rollOverDisplay": false,
        "useHandCursor": true,
        "maps": [],
        "id": "overlay_C1_0",
        "hasChanges": true
      },
      {
        "excludeClickGoMode": false,
        "class": "HotspotPanoramaOverlayEditable",
        "areas": [
          "this.HotspotPanoramaOverlayArea_D0_0"
        ],
        "rollOverDisplay": false,
        "useHandCursor": true,
        "items": [
          {
            "x": 1314.7150873377134,
            "class": "HotspotPanoramaOverlayBitmapImage",
            "transparencyActive": true,
            "y": 91.71195652173913,
            "label": "Image",
            "horizontalAlign": "center",
            "scaleMode": "fit_inside",
            "verticalAlign": "middle",
            "factorWidth": 1.071877180739707,
            "libraryData": {
              "type": "round",
              "name": "blue",
              "family": "photos",
              "element": "IHotspotOverlayBitmapImage"
            },
            "width": 33.3333,
            "distance": 100,
            "factorHeight": 1.071877180739707,
            "pitch": 66.4169254658385,
            "hfov": 7.616601683506721,
            "yaw": 154.24959847568985,
            "height": 30,
            "path": "hotspots/Hotspot_7E39A010_7A6C_4A10_41CC_55298DA3B325.png"
          }
        ],
        "id": "overlay_D0_0",
        "hasChanges": true,
        "maps": []
      },
      {
        "rotationY": 0,
        "class": "PopupPanoramaOverlayEditable",
        "hideEasing": "cubic_out",
        "showEasing": "cubic_in",
        "popupMaxWidth": "95%",
        "id": "popup_D0_0",
        "rotationZ": 0,
        "hasChanges": true,
        "popupMaxHeight": "95%",
        "showDuration": 500,
        "hideDuration": 500,
        "rotationX": 0,
        "popupDistance": 100,
        "path": "1990454.jpg"
      },
      {
        "excludeClickGoMode": false,
        "class": "HotspotPanoramaOverlayEditable",
        "areas": [
          "this.HotspotPanoramaOverlayArea_D0_1"
        ],
        "rollOverDisplay": false,
        "useHandCursor": true,
        "items": [
          {
            "x": 1866.6974516223065,
            "class": "HotspotPanoramaOverlayBitmapImage",
            "transparencyActive": true,
            "y": 100.20380434782608,
            "label": "Image",
            "horizontalAlign": "center",
            "scaleMode": "fit_inside",
            "verticalAlign": "middle",
            "factorWidth": 1.071877180739707,
            "libraryData": {
              "type": "round",
              "name": "blue",
              "family": "photos",
              "element": "IHotspotOverlayBitmapImage"
            },
            "width": 33.3333,
            "distance": 100,
            "factorHeight": 1.071877180739707,
            "pitch": 64.23330745341615,
            "hfov": 7.616601683506721,
            "yaw": 294.5840978700779,
            "height": 30,
            "path": "hotspots/Hotspot_7E39A010_7A6C_4A10_41CC_55298DA3B325.png"
          }
        ],
        "id": "overlay_D0_1",
        "hasChanges": true,
        "maps": []
      },
      {
        "rotationY": 0,
        "class": "PopupPanoramaOverlayEditable",
        "hideEasing": "cubic_out",
        "showEasing": "cubic_in",
        "popupMaxWidth": "95%",
        "id": "popup_D0_1",
        "rotationZ": 0,
        "hasChanges": true,
        "popupMaxHeight": "95%",
        "showDuration": 500,
        "hideDuration": 500,
        "rotationX": 0,
        "popupDistance": 100,
        "path": "2776322.jpg"
      },
      {
        "class": "HotspotPanoramaOverlayArea",
        "id": "HotspotPanoramaOverlayArea_C0_0",
        "behaviours": [
          {
            "media": "this.panorama_47FE5A9D_4E21_4956_41A5_92D82D1E8740",
            "class": "PanoramaBehaviour",
            "event": "click",
            "startPointView": {
              "type": "smartPoint",
              "class": "StartPointView"
            },
            "sentences": [],
            "inComponent": "this.MainViewer",
            "action": "openPanorama",
            "where": "inViewer"
          }
        ]
      },
      {
        "class": "HotspotPanoramaOverlayArea",
        "id": "HotspotPanoramaOverlayArea_C1_0",
        "behaviours": [
          {
            "media": "this.panorama_44D4D1A2_4E21_7B73_41CC_EDE1070CE037",
            "class": "PanoramaBehaviour",
            "event": "click",
            "startPointView": {
              "type": "smartPoint",
              "class": "StartPointView"
            },
            "sentences": [],
            "inComponent": "this.MainViewer",
            "action": "openPanorama",
            "where": "inViewer"
          }
        ]
      },
      {
        "id": "HotspotPanoramaOverlayArea_D0_0",
        "class": "HotspotPanoramaOverlayArea",
        "behaviours": [
          {
            "autoCloseIfNotInteraction": false,
            "overlay": "this.popup_D0_0",
            "class": "PopupPanoramaOverlayBehaviour",
            "event": "click",
            "sentences": [],
            "stopBackgroundAudio": false,
            "overlayerCallee": "this.panorama_44D4D1A2_4E21_7B73_41CC_EDE1070CE037",
            "closeButton": "this.CloseButton_D0_0",
            "action": "openPopupPanoramaOverlay",
            "milliseconds": 10000
          }
        ]
      },
      {
        "shadowSpread": 1,
        "name": "CloseButton4187",
        "rollOverIconColor": 6710886,
        "toolTipShadowColor": 3355443,
        "toolTipHorizontalAlign": "center",
        "toolTipFontStyle": "normal",
        "toolTipTextShadowAngle": 0,
        "paddingBottom": 5,
        "id": "CloseButton_D15309A1_D0_0",
        "toolTipBackgroundTransparent": false,
        "toolTipTextShadowBlurRadius": 3,
        "paddingLeft": 5,
        "shadowColor": 0,
        "toolTipShadowOpacity": 1,
        "toolTipShadowBlurRadius": 3,
        "propagateClick": false,
        "toolTipShadowDistance": 0,
        "backgroundOpacity": 0.3,
        "toolTipBorderSize": 1,
        "gap": 5,
        "verticalAlign": "middle",
        "toolTipFontWeight": "normal",
        "paddingRight": 5,
        "iconWidth": 20,
        "arrangement": "horizontal",
        "toolTipFontSize": "1.11vmin",
        "iconLineWidth": 5,
        "shadowBlurRadius": 6,
        "horizontalAlign": "center",
        "toolTipPaddingTop": 4,
        "borderColor": 0,
        "borderSize": 0,
        "toolTipShadowSpread": 0,
        "iconHeight": 20,
        "fontFamily": "Arial",
        "toolTipBorderColor": 7763574,
        "pressedIconColor": 8947848,
        "toolTipPaddingLeft": 6,
        "textDecoration": "none",
        "backgroundColor": [
          14540253,
          15658734,
          16777215
        ],
        "toolTipShadowAngle": 45,
        "class": "CloseButton",
        "toolTipOpacity": 1,
        "fontSize": "1.29vmin",
        "asHotspotVideo": false,
        "mode": "push",
        "toolTipBorderRadius": 3,
        "toolTipTextShadowDistance": 0,
        "minHeight": 0,
        "backgroundColorAlphas": [
          1,
          1,
          1
        ],
        "minWidth": 0,
        "toolTipPaddingBottom": 4,
        "borderRadius": 0,
        "shadowDistance": 3,
        "fontStyle": "normal",
        "shadow": false,
        "iconColor": 0,
        "toolTipTextShadowOpacity": 0,
        "backgroundColorDirection": "vertical",
        "fontColor": 16777215,
        "backgroundColorRatios": [
          0,
          25,
          255
        ],
        "toolTipDisplayTime": 600,
        "visible": true,
        "toolTipPaddingRight": 6,
        "toolTipFontFamily": "Arial",
        "paddingTop": 5,
        "toolTipFontColor": 6316128,
        "cursor": "hand",
        "toolTipTextShadowSpread": 0,
        "fontWeight": "normal",
        "toolTipTextShadowColor": 0,
        "toolTipBackgroundColor": 16185078
      },
      {
        "id": "HotspotPanoramaOverlayArea_D0_1",
        "class": "HotspotPanoramaOverlayArea",
        "behaviours": [
          {
            "autoCloseIfNotInteraction": false,
            "overlay": "this.popup_D0_1",
            "class": "PopupPanoramaOverlayBehaviour",
            "event": "click",
            "sentences": [],
            "stopBackgroundAudio": false,
            "overlayerCallee": "this.panorama_44D4D1A2_4E21_7B73_41CC_EDE1070CE037",
            "closeButton": "this.CloseButton_D0_1",
            "action": "openPopupPanoramaOverlay",
            "milliseconds": 10000
          }
        ]
      },
      {
        "shadowSpread": 1,
        "name": "CloseButton4187",
        "rollOverIconColor": 6710886,
        "toolTipShadowColor": 3355443,
        "toolTipHorizontalAlign": "center",
        "toolTipFontStyle": "normal",
        "toolTipTextShadowAngle": 0,
        "paddingBottom": 5,
        "id": "CloseButton_D15309A1_D0_1",
        "toolTipBackgroundTransparent": false,
        "toolTipTextShadowBlurRadius": 3,
        "paddingLeft": 5,
        "shadowColor": 0,
        "toolTipShadowOpacity": 1,
        "toolTipShadowBlurRadius": 3,
        "propagateClick": false,
        "toolTipShadowDistance": 0,
        "backgroundOpacity": 0.3,
        "toolTipBorderSize": 1,
        "gap": 5,
        "verticalAlign": "middle",
        "toolTipFontWeight": "normal",
        "paddingRight": 5,
        "iconWidth": 20,
        "arrangement": "horizontal",
        "toolTipFontSize": "1.11vmin",
        "iconLineWidth": 5,
        "shadowBlurRadius": 6,
        "horizontalAlign": "center",
        "toolTipPaddingTop": 4,
        "borderColor": 0,
        "borderSize": 0,
        "toolTipShadowSpread": 0,
        "iconHeight": 20,
        "fontFamily": "Arial",
        "toolTipBorderColor": 7763574,
        "pressedIconColor": 8947848,
        "toolTipPaddingLeft": 6,
        "textDecoration": "none",
        "backgroundColor": [
          14540253,
          15658734,
          16777215
        ],
        "toolTipShadowAngle": 45,
        "class": "CloseButton",
        "toolTipOpacity": 1,
        "fontSize": "1.29vmin",
        "asHotspotVideo": false,
        "mode": "push",
        "toolTipBorderRadius": 3,
        "toolTipTextShadowDistance": 0,
        "minHeight": 0,
        "backgroundColorAlphas": [
          1,
          1,
          1
        ],
        "minWidth": 0,
        "toolTipPaddingBottom": 4,
        "borderRadius": 0,
        "shadowDistance": 3,
        "fontStyle": "normal",
        "shadow": false,
        "iconColor": 0,
        "toolTipTextShadowOpacity": 0,
        "backgroundColorDirection": "vertical",
        "fontColor": 16777215,
        "backgroundColorRatios": [
          0,
          25,
          255
        ],
        "toolTipDisplayTime": 600,
        "visible": true,
        "toolTipPaddingRight": 6,
        "toolTipFontFamily": "Arial",
        "paddingTop": 5,
        "toolTipFontColor": 6316128,
        "cursor": "hand",
        "toolTipTextShadowSpread": 0,
        "fontWeight": "normal",
        "toolTipTextShadowColor": 0,
        "toolTipBackgroundColor": 16185078
      }
    ],
    "backgroundColorDirection": "vertical",
    "backgroundColorRatios": [
      0
    ],
    "backgroundPreloadEnabled": true,
    "toolTipDisplayTime": 600,
    "desktopMipmappingEnabled": false,
    "visible": true,
    "toolTipPaddingRight": 6,
    "toolTipFontFamily": "Arial",
    "mouseWheelEnabled": true,
    "paddingTop": 0,
    "toolTipFontColor": 6316128,
    "toolTipTextShadowSpread": 0,
    "toolTipTextShadowColor": 0,
    "toolTipBackgroundColor": 16185078
  },
  "forceGeneralSkinIPad": false,
  "publishVideo360Properties": {},
  "medias": [
    "this.panorama_44D4D1A2_4E21_7B73_41CC_EDE1070CE037",
    "this.panorama_47FE5A9D_4E21_4956_41A5_92D82D1E8740"
  ],
  "surfaceSelectionSensitivity": 1,
  "tdvHostingCredentials": {
    "class": "TDVHostingCredentials"
  },
  "panoramaZoomEnabled": true,
  "surfaceSelectionHotspotMode": "circleEnabled",
  "publishVideo360": false,
  "muteSoundAtStart": false,
  "textToSpeechConfig": {
    "speechOnTooltip": false,
    "pitch": 1,
    "stopBackgroundAudio": false,
    "class": "TextToSpeechConfig",
    "speechOnQuizQuestion": false,
    "speechOnInfoWindow": false,
    "volume": 1,
    "rate": 1
  },
  "publishAutoexecutable": false,
  "enableTdvTourAnalytics": false,
  "optimizeForVR": true,
  "analyticsAnonymizeIP": true,
  "publishAutoexecutableWindows": true,
  "initialScale": 0.5,
  "publishScorm": false,
  "publishWeb": true,
  "include360SocialIcon": true,
  "panoramaTouchControlMode": "drag_rotation",
  "surfaceSelectionEnabled": false,
  "publishAutoexecutableMac": true,
  "exportVideoToAdaptive": false,
  "enableSubtitles": true,
  "preloadPlayer": {
    "vrPolyfillScale": 0.75,
    "name": "Player613",
    "toolTipShadowColor": 3355443,
    "toolTipShadowBlurRadius": 3,
    "scrollBarMargin": 2,
    "toolTipFontStyle": "normal",
    "toolTipTextShadowAngle": 0,
    "paddingBottom": 0,
    "id": "Player_45428D56_4E21_CBD2_41D1_05DDAE1D641C",
    "toolTipBackgroundTransparent": false,
    "toolTipTextShadowBlurRadius": 3,
    "overflow": "hidden",
    "paddingLeft": 0,
    "toolTipShadowOpacity": 1,
    "toolTipHorizontalAlign": "center",
    "propagateClick": false,
    "toolTipShadowDistance": 0,
    "backgroundOpacity": 1,
    "toolTipBorderSize": 1,
    "gap": 10,
    "verticalAlign": "top",
    "toolTipFontWeight": "normal",
    "paddingRight": 0,
    "defaultVRPointer": "laser",
    "scrollBarWidth": 10,
    "arrangement": "absolute",
    "toolTipFontSize": "1.11vmin",
    "mediaActivationMode": "window",
    "horizontalAlign": "left",
    "toolTipPaddingTop": 4,
    "borderSize": 0,
    "scrollBarVisible": "rollOver",
    "toolTipShadowSpread": 0,
    "device2Children": {
      "general": [
        "this.HTMLText_4720EEBE_4E20_C952_41AF_2A8B54294CA0"
      ]
    },
    "scrollBarOpacity": 0.5,
    "toolTipBorderColor": 7763574,
    "downloadEnabled": false,
    "class": "Player",
    "toolTipPaddingLeft": 6,
    "mobileMipmappingEnabled": false,
    "backgroundColor": [
      16777215
    ],
    "toolTipShadowAngle": 45,
    "width": "100%",
    "toolTipOpacity": 1,
    "height": "100%",
    "asHotspotVideo": false,
    "toolTipBorderRadius": 3,
    "toolTipTextShadowDistance": 0,
    "minHeight": 20,
    "scrollBarColor": 0,
    "backgroundColorAlphas": [
      1
    ],
    "minWidth": 20,
    "toolTipPaddingBottom": 4,
    "borderRadius": 0,
    "shadow": false,
    "landscapeModeMobile": "mobile",
    "percentHeight": 100,
    "percentWidth": 100,
    "toolTipTextShadowOpacity": 0,
    "contentOpaque": false,
    "definitions": [],
    "backgroundColorDirection": "vertical",
    "backgroundColorRatios": [
      0
    ],
    "backgroundPreloadEnabled": true,
    "toolTipDisplayTime": 600,
    "desktopMipmappingEnabled": false,
    "visible": true,
    "toolTipPaddingRight": 6,
    "toolTipFontFamily": "Arial",
    "mouseWheelEnabled": true,
    "paddingTop": 0,
    "toolTipFontColor": 6316128,
    "toolTipTextShadowSpread": 0,
    "toolTipTextShadowColor": 0,
    "toolTipBackgroundColor": 16185078
  },
  "publishGSV": false,
  "enableLocaleAutodetection": true,
  "previewLevel": "yes",
  "publishTDVCloud": false,
  "gyroscopeVerticalDraggingEnabled": true,
  "locales": [
    {
      "class": "Locale",
      "language": "ja",
      "data": {
        "HTMLText_4720EEBE_4E20_C952_41AF_2A8B54294CA0.html": {
          "value": "<P ALIGN=\"center\"><FONT FACE=\"Arial\" SIZE=\"1.6666666666666665vmin\" COLOR=\"#777777\" LETTERSPACING=\"0vmin\" KERNING=\"1\">Loading virtual tour. Please wait...</FONT></P>",
          "class": "LocaleValue"
        },
        "tour.name": {
          "value": "Untitled 246",
          "class": "LocaleValue"
        },
        "panorama_47FE5A9D_4E21_4956_41A5_92D82D1E8740.label": {
          "value": "R0010548",
          "class": "LocaleValue"
        },
        "panorama_44D4D1A2_4E21_7B73_41CC_EDE1070CE037.label": {
          "value": "R0010547",
          "class": "LocaleValue"
        }
      }
    }
  ],
  "additionalMedias": [],
  "saveAs": "C:\\Users\\root\\Documents\\walk\\3dview_automation\\3dvista_edit_code_new\\project\\test.vtp",
  "initializationMode": "onReady",
  "uid": "46D06EB6-4E20-C952-41BA-D0B5A77038BF",
  "mainPlayListSameSpotForPanoramas": false,
  "class": "ShowProject",
  "exportiOSLegacy": false,
  "displayTooltipInSurfaceSelection": true,
  "arrowKeysAction": "translate",
  "publishAutoexecutableWithCompression": false
}